# Generated by Django 4.1.5 on 2023-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_icepops", "0002_icepop_description_icepop_special_price_and_more"),
        ("app_general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="icepop_set",
            field=models.ManyToManyField(to="app_icepops.icepop"),
        ),
    ]
