# Generated by Django 4.1.5 on 2023-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Icepop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("is_premium", models.BooleanField(null=True)),
                ("promo_end_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
