# Generated by Django 4.1.5 on 2023-01-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_icepops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="icepop",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="icepop",
            name="special_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="icepop",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="icepop",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
