# Generated by Django 4.1.5 on 2023-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_icepops", "0003_alter_icepop_promo_end_at_alter_icepop_special_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="icepop",
            name="image_relative_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
